# Generated by Django 3.2.12 on 2022-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptonews',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
